"use client";

import {
  Hash,
  Layers,
  Link2,
  List,
  Network,
  SquareStack,
  TreePine,
} from "lucide-react";
import ProblemCatalogPage, {
  type CategoryStats,
  type Problem,
} from "@/app/learn/_shared/ProblemCatalogPage";

/* ------------------------------------------------------------------ */
/*  Static data                                                        */
/* ------------------------------------------------------------------ */

const categories: CategoryStats[] = [
  {
    name: "Array",
    icon: <List className="h-4 w-4" />,
    total: 22,
    solved: 16,
    color: "text-blue-500",
  },
  {
    name: "Linked List",
    icon: <Link2 className="h-4 w-4" />,
    total: 18,
    solved: 10,
    color: "text-emerald-500",
  },
  {
    name: "Stack & Queue",
    icon: <SquareStack className="h-4 w-4" />,
    total: 16,
    solved: 12,
    color: "text-amber-500",
  },
  {
    name: "Tree",
    icon: <TreePine className="h-4 w-4" />,
    total: 25,
    solved: 8,
    color: "text-purple-500",
  },
  {
    name: "Graph",
    icon: <Network className="h-4 w-4" />,
    total: 20,
    solved: 5,
    color: "text-rose-500",
  },
  {
    name: "Hash Table",
    icon: <Hash className="h-4 w-4" />,
    total: 15,
    solved: 11,
    color: "text-cyan-500",
  },
];

const problems: Problem[] = [
  // Array
  {
    id: 1,
    title: "Two Sum",
    slug: "two-sum",
    difficulty: "easy",
    acceptance: 95,
    status: "solved",
    tags: ["Array", "Hash Table"],
    category: "Array",
  },
  {
    id: 2,
    title: "Best Time to Buy and Sell Stock",
    slug: "buy-sell-stock",
    difficulty: "easy",
    acceptance: 88,
    status: "solved",
    tags: ["Array"],
    category: "Array",
  },
  {
    id: 3,
    title: "Contains Duplicate",
    slug: "contains-duplicate",
    difficulty: "easy",
    acceptance: 91,
    status: "solved",
    tags: ["Array", "Hash Table"],
    category: "Array",
  },
  {
    id: 4,
    title: "Product of Array Except Self",
    slug: "product-except-self",
    difficulty: "medium",
    acceptance: 66,
    status: "attempted",
    tags: ["Array"],
    category: "Array",
  },
  {
    id: 5,
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    difficulty: "medium",
    acceptance: 70,
    status: "solved",
    tags: ["Array"],
    category: "Array",
  },
  {
    id: 6,
    title: "3Sum",
    slug: "3sum",
    difficulty: "medium",
    acceptance: 55,
    status: "unsolved",
    tags: ["Array"],
    category: "Array",
  },
  {
    id: 7,
    title: "Trapping Rain Water",
    slug: "trapping-rain-water",
    difficulty: "hard",
    acceptance: 42,
    status: "unsolved",
    tags: ["Array", "Stack & Queue"],
    category: "Array",
  },

  // Linked List
  {
    id: 8,
    title: "Reverse Linked List",
    slug: "reverse-linked-list",
    difficulty: "easy",
    acceptance: 90,
    status: "solved",
    tags: ["Linked List"],
    category: "Linked List",
  },
  {
    id: 9,
    title: "Merge Two Sorted Lists",
    slug: "merge-two-sorted-lists",
    difficulty: "easy",
    acceptance: 87,
    status: "solved",
    tags: ["Linked List"],
    category: "Linked List",
  },
  {
    id: 10,
    title: "Linked List Cycle",
    slug: "linked-list-cycle",
    difficulty: "easy",
    acceptance: 85,
    status: "solved",
    tags: ["Linked List"],
    category: "Linked List",
  },
  {
    id: 11,
    title: "Remove Nth Node From End",
    slug: "remove-nth-node",
    difficulty: "medium",
    acceptance: 62,
    status: "attempted",
    tags: ["Linked List"],
    category: "Linked List",
  },
  {
    id: 12,
    title: "Reorder List",
    slug: "reorder-list",
    difficulty: "medium",
    acceptance: 55,
    status: "unsolved",
    tags: ["Linked List"],
    category: "Linked List",
  },
  {
    id: 13,
    title: "Merge k Sorted Lists",
    slug: "merge-k-sorted-lists",
    difficulty: "hard",
    acceptance: 40,
    status: "unsolved",
    tags: ["Linked List"],
    category: "Linked List",
    isPremium: true,
  },

  // Stack & Queue
  {
    id: 14,
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    difficulty: "easy",
    acceptance: 92,
    status: "solved",
    tags: ["Stack & Queue"],
    category: "Stack & Queue",
  },
  {
    id: 15,
    title: "Min Stack",
    slug: "min-stack",
    difficulty: "medium",
    acceptance: 72,
    status: "solved",
    tags: ["Stack & Queue"],
    category: "Stack & Queue",
  },
  {
    id: 16,
    title: "Evaluate Reverse Polish Notation",
    slug: "reverse-polish-notation",
    difficulty: "medium",
    acceptance: 64,
    status: "attempted",
    tags: ["Stack & Queue"],
    category: "Stack & Queue",
  },
  {
    id: 17,
    title: "Implement Queue Using Stacks",
    slug: "queue-using-stacks",
    difficulty: "easy",
    acceptance: 85,
    status: "solved",
    tags: ["Stack & Queue"],
    category: "Stack & Queue",
  },
  {
    id: 18,
    title: "Sliding Window Maximum",
    slug: "sliding-window-max",
    difficulty: "hard",
    acceptance: 38,
    status: "unsolved",
    tags: ["Stack & Queue", "Array"],
    category: "Stack & Queue",
  },

  // Tree
  {
    id: 19,
    title: "Invert Binary Tree",
    slug: "invert-binary-tree",
    difficulty: "easy",
    acceptance: 93,
    status: "solved",
    tags: ["Tree"],
    category: "Tree",
  },
  {
    id: 20,
    title: "Maximum Depth of Binary Tree",
    slug: "max-depth-binary-tree",
    difficulty: "easy",
    acceptance: 91,
    status: "solved",
    tags: ["Tree"],
    category: "Tree",
  },
  {
    id: 21,
    title: "Same Tree",
    slug: "same-tree",
    difficulty: "easy",
    acceptance: 89,
    status: "solved",
    tags: ["Tree"],
    category: "Tree",
  },
  {
    id: 22,
    title: "Binary Tree Level Order Traversal",
    slug: "level-order-traversal",
    difficulty: "medium",
    acceptance: 68,
    status: "attempted",
    tags: ["Tree"],
    category: "Tree",
  },
  {
    id: 23,
    title: "Validate Binary Search Tree",
    slug: "validate-bst",
    difficulty: "medium",
    acceptance: 55,
    status: "unsolved",
    tags: ["Tree"],
    category: "Tree",
  },
  {
    id: 24,
    title: "Serialize and Deserialize Binary Tree",
    slug: "serialize-deserialize-tree",
    difficulty: "hard",
    acceptance: 35,
    status: "unsolved",
    tags: ["Tree"],
    category: "Tree",
    isPremium: true,
  },

  // Graph
  {
    id: 25,
    title: "Number of Islands",
    slug: "number-of-islands",
    difficulty: "medium",
    acceptance: 62,
    status: "solved",
    tags: ["Graph"],
    category: "Graph",
  },
  {
    id: 26,
    title: "Clone Graph",
    slug: "clone-graph",
    difficulty: "medium",
    acceptance: 58,
    status: "attempted",
    tags: ["Graph"],
    category: "Graph",
  },
  {
    id: 27,
    title: "Course Schedule",
    slug: "course-schedule",
    difficulty: "medium",
    acceptance: 52,
    status: "unsolved",
    tags: ["Graph"],
    category: "Graph",
  },
  {
    id: 28,
    title: "Pacific Atlantic Water Flow",
    slug: "pacific-atlantic",
    difficulty: "medium",
    acceptance: 48,
    status: "unsolved",
    tags: ["Graph"],
    category: "Graph",
  },
  {
    id: 29,
    title: "Alien Dictionary",
    slug: "alien-dictionary",
    difficulty: "hard",
    acceptance: 32,
    status: "unsolved",
    tags: ["Graph"],
    category: "Graph",
    isPremium: true,
  },

  // Hash Table
  {
    id: 30,
    title: "Valid Anagram",
    slug: "valid-anagram",
    difficulty: "easy",
    acceptance: 94,
    status: "solved",
    tags: ["Hash Table"],
    category: "Hash Table",
  },
  {
    id: 31,
    title: "Group Anagrams",
    slug: "group-anagrams",
    difficulty: "medium",
    acceptance: 70,
    status: "solved",
    tags: ["Hash Table"],
    category: "Hash Table",
  },
  {
    id: 32,
    title: "Top K Frequent Elements",
    slug: "top-k-frequent",
    difficulty: "medium",
    acceptance: 65,
    status: "attempted",
    tags: ["Hash Table", "Array"],
    category: "Hash Table",
  },
  {
    id: 33,
    title: "LRU Cache",
    slug: "lru-cache",
    difficulty: "medium",
    acceptance: 48,
    status: "unsolved",
    tags: ["Hash Table", "Linked List"],
    category: "Hash Table",
  },
];

export default function DataStructurePage() {
  return (
    <ProblemCatalogPage
      title="Data Structures"
      description="Master fundamental data structures through hands-on practice problems."
      headerIcon={<Layers className="h-6 w-6 text-primary" />}
      basePath="/learn/data-structure"
      categories={categories}
      problems={problems}
    />
  );
}
